language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install thinc"
  - "rm -rf thinc/"
# command to run tests
script: "py.test tests/"
