language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  python setup.py build_ext --inplace &&
  pip install -r requirements.txt 
# command to run tests
script: "py.test tests/"
