language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - "pip install --upgrade setuptools"
  - "pip install cython"
  - "python setup.py build_ext --inplace"
# command to run tests
script: "py.test tests/"
